#!/bin/bash

_kill_procs() {
  kill -TERM $chproc
  wait $chproc
  kill -TERM $xvfb
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

XVFB_WHD=${XVFB_WHD:-1024x768x16}

# Start Xvfb
Xvfb :99 -ac -screen 1 $XVFB_WHD +extension RANDR -nolisten tcp &
xvfb=$!

export DISPLAY=:99

google-chrome-stable --no-sandbox $@ &
chproc=$!

wait $chproc
wait $xvfb
